flowchart TD
    ImgFlip_UI[图片翻转界面]
    ImgFlip_UI --> ImgFlip_Upload[上传图片]
    ImgFlip_UI --> ImgFlip_Set[选择翻转方向]
    ImgFlip_UI --> ImgFlip_Apply[翻转按钮]
    ImgFlip_UI --> ImgFlip_Result[翻转结果/下载]
    style ImgFlip_UI fill:#f9f,stroke:#333,stroke-width:2px 