flowchart TD
    ImgRotate_UI[图片旋转界面]
    ImgRotate_UI --> ImgRotate_Upload[上传图片]
    ImgRotate_UI --> ImgRotate_Set[设置旋转角度]
    ImgRotate_UI --> ImgRotate_Apply[旋转按钮]
    ImgRotate_UI --> ImgRotate_Result[旋转结果/下载]
    style ImgRotate_UI fill:#f9f,stroke:#333,stroke-width:2px 