flowchart TD
    ImgCrop_UI[图片裁剪界面]
    ImgCrop_UI --> ImgCrop_Upload[上传图片]
    ImgCrop_UI --> ImgCrop_Select[选择裁剪区域]
    ImgCrop_UI --> ImgCrop_Crop[裁剪按钮]
    ImgCrop_UI --> ImgCrop_Result[裁剪结果/下载]
    style ImgCrop_UI fill:#f9f,stroke:#333,stroke-width:2px 