flowchart TD
    ImgCompress_UI[图片压缩界面]
    ImgCompress_UI --> ImgCompress_Upload[上传图片]
    ImgCompress_UI --> ImgCompress_Set[设置压缩参数]
    ImgCompress_UI --> ImgCompress_Convert[压缩按钮]
    ImgCompress_UI --> ImgCompress_Result[压缩结果/下载]
    style ImgCompress_UI fill:#f9f,stroke:#333,stroke-width:2px 