flowchart TD
    ImgSharpen_UI[图片锐化界面]
    ImgSharpen_UI --> ImgSharpen_Upload[上传图片]
    ImgSharpen_UI --> ImgSharpen_Set[设置锐化参数]
    ImgSharpen_UI --> ImgSharpen_Apply[锐化按钮]
    ImgSharpen_UI --> ImgSharpen_Result[锐化结果/下载]
    style ImgSharpen_UI fill:#f9f,stroke:#333,stroke-width:2px 