flowchart TD
    ImgBlur_UI[图片模糊界面]
    ImgBlur_UI --> ImgBlur_Upload[上传图片]
    ImgBlur_UI --> ImgBlur_Set[设置模糊参数]
    ImgBlur_UI --> ImgBlur_Apply[模糊按钮]
    ImgBlur_UI --> ImgBlur_Result[模糊结果/下载]
    style ImgBlur_UI fill:#f9f,stroke:#333,stroke-width:2px 