flowchart TD
    ImgMirror_UI[图片镜像界面]
    ImgMirror_UI --> ImgMirror_Upload[上传图片]
    ImgMirror_UI --> ImgMirror_Set[选择镜像方式]
    ImgMirror_UI --> ImgMirror_Apply[镜像按钮]
    ImgMirror_UI --> ImgMirror_Result[镜像结果/下载]
    style ImgMirror_UI fill:#f9f,stroke:#333,stroke-width:2px 