flowchart TD
    ImgBright_UI[图片亮度界面]
    ImgBright_UI --> ImgBright_Upload[上传图片]
    ImgBright_UI --> ImgBright_Set[设置亮度参数]
    ImgBright_UI --> ImgBright_Apply[调整按钮]
    ImgBright_UI --> ImgBright_Result[亮度调整结果/下载]
    style ImgBright_UI fill:#f9f,stroke:#333,stroke-width:2px 