flowchart TD
    FCopy_UI[文件复制界面]
    FCopy_UI --> FCopy_List[可复制文件列表]
    FCopy_UI --> FCopy_Dest[目标位置选择]
    FCopy_UI --> FCopy_Confirm[复制按钮]
    FCopy_UI --> FCopy_Result[复制结果提示]
    style FCopy_UI fill:#f9f,stroke:#333,stroke-width:2px 