flowchart TD
    FDel_UI[文件删除界面]
    FDel_UI --> FDel_List[可删除文件列表]
    FDel_UI --> FDel_DeleteBtn[删除按钮]
    FDel_UI --> FDel_Confirm[删除确认弹窗]
    FDel_UI --> FDel_Result[删除结果提示]
    style FDel_UI fill:#f9f,stroke:#333,stroke-width:2px 